-- require("alpha").setup(require("alpha.themes.startify").config)

local alpha = require("alpha")
local dashboard = require("alpha.themes.dashboard")

-- Set header
dashboard.section.header.val = {
	"        .-::::-.        ",
	"    `.://::::::/+/-`    ",
	"  `//-`` -///::``.:+/`  ",
	" `+:-:```.-::..`  -.:+` ",
	" /-`-`:..--::--..``. -: ",
	"`:`  `.-://++//--.`  `:`",
	"`-   `.-:/+ss//:-.`   :`",
	" -`  `.--:////:--.`  `: ",
	" .-   `..--::--..`   -. ",
	"  ./.   ``....``   `+-  ",
	"   .:-``         `-:.   ",
	"     `----::://:-.`     ",
	"         `.---.         ",
}
dashboard.section.header.val = {
	"                                                     ",
	"  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗ ",
	"  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║ ",
	"  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║ ",
	"  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║ ",
	"  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║ ",
	"  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝ ",
	"                                                     ",
}

-- silly quotes generated by chatGPT
local quotes = {
	"Why do programmers prefer dark mode? Because light attracts bugs.",
	"Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25!",
	"I don't always test my code, but when I do, I do it in production.",
	"Programming is easy, it's the documentation that's hard.",
	"The generation of random numbers is too important to be left to chance.",
	"If you think math is hard, try web design.",
	"Why do programmers always get Christmas and Halloween mixed up? Because Oct 31 == Dec 25!",
	"There are only 10 types of people in the world: those who understand binary, and those who don't.",
	"Why do Java developers wear glasses? Because they don't C#!",
	"Debugging: Removing the needles from the haystack.",
	"I have a joke on programming, but it only works on my machine.",
	"Software developers like to solve problems. If there are no problems available, they will create their own.",
	"Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
	"I would love to change the world, but they won't give me the source code.",
	"Real programmers count from 0.",
	"The best thing about a boolean is even if you are wrong, you are only off by a bit.",
	"The great thing about programming is that you never finish learning. The bad thing about programming is that you never finish learning.",
	"Why do programmers hate nature? It has too many bugs!",
	"In theory, there is no difference between theory and practice. But in practice, there is.",
}

dashboard.section.footer.val = {
	quotes[math.random(#quotes)],
}

-- Set menu
dashboard.section.buttons.val = {
	dashboard.button("f", "󰭎 Telescope find_files", ":Telescope find_files <CR>"),
	dashboard.button("g", " Telescope git_files", ":Telescope git_files <CR>"),
	dashboard.button("d", " Telescope live_grep", ":Telescope live_grep <CR>"),
	dashboard.button("u", "󰚰 Lazy", ":Lazy <CR>"),
	dashboard.button("m", "󰟾 Mason", ":Mason <CR>"),
	dashboard.button("t", "󱐚 Treesitter update", ":TSUpdate <CR>"),
	dashboard.button("q", "󰩈 quit", ":q <CR>"),
}

-- Send config to alpha
alpha.setup(dashboard.opts)

-- Disable folding on alpha buffer
vim.cmd([[
    autocmd FileType alpha setlocal nofoldenable
]])
